### ISSUE TITLE
道理我都懂，可是我不会看五线谱。

### ISSUE THREAD

**Issue by solomon-8** [niffler-bkkkkk/violinspectrum#1]
tql wfxx yqzh 

我想听小提琴怎么办？

**Comment by GooeyNyan** [comment]
Github is for programmer to communicate with others. Not for ENTERTAINMENT!
Pls dlt asap.
![image](https://user-images.githubusercontent.com/16070774/47225376-83b3a380-d3f0-11e8-9de7-5fde8a641754.png)

**Comment by solomon-8** [comment]
I'm just communicate with others.

As the github help page say about issue:Use issues to track ideas, enhancements, tasks, or bugs for work on GitHub.
https://help.github.com/articles/about-issues/

I'm interested in this repository and track my idea to the owner with issue,i think that's a suitable operation , According to the help page.

And I have problem at dlt , just found a button name close issue.

Can you teach me how to hack the github and delete this issue? thx.

wish you a happy life.

Though i just want to piyixia. ξ( ✿＞◡❛)
